apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: agenda-service 
spec:
  template:
    spec:
      containers:
        - image: salaboy/agenda-service-0967b907d9920c99918e2b91b91937b3:v1.0.0 
          env:
          - name: KAFKA_URL
            value: kafka.default.svc.cluster.local
          - name: REDIS_HOST
            value: redis-master.default.svc.cluster.local
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis
                key: redis-password  
          - name: POD_NODENAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: POD_SERVICE_ACCOUNT
            valueFrom:
              fieldRef:
                fieldPath: spec.serviceAccountName    

