apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: frontend
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - image: salaboy/frontend-go-1739aa83b5e69d4ccb8a5615830ae66c:v1.0.0
          env:
          - name: KAFKA_URL
            value: kafka.default.svc.cluster.local
          - name: AGENDA_SERVICE_URL
            value: http://agenda-service.default.svc.cluster.local
          - name: C4P_SERVICE_URL
            value: http://c4p-service.default.svc.cluster.local
          - name: NOTIFICATIONS_SERVICE_URL
            value: http://notifications-service.default.svc.cluster.local    
          - name: POD_NODENAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: POD_SERVICE_ACCOUNT
            valueFrom:
              fieldRef:
                fieldPath: spec.serviceAccountName    

