
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: api-server-to-service-deployment-function
  namespace: dora-cloudevents
spec:
  template:
    spec:
      containers:
        - image: ko://function-api-server-to-service-deployment.go
          env:
            - name: CDEVENTS_ENDPOINT_URL
              value: http://cdevents-raw-endpoint.dora-cloudevents.svc.cluster.local

---

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cloudevents-raw-endpoint
  namespace: dora-cloudevents
spec:
  template:
    spec:
      containers:
        - image: ko://cloudevents-endpoint.go
          env:
          - name: POSTGRESQL_HOST
            value: postgresql
          - name: POSTGRESQL_PASS
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: postgres-password


---

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cdevents-raw-endpoint
  namespace: dora-cloudevents
spec:
  template:
    spec:
      containers:
        - image: ko://cdevents-endpoint.go
          env:
            - name: POSTGRESQL_HOST
              value: postgresql
            - name: POSTGRESQL_PASS
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: postgres-password


---

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: dora-frequency-endpoint
  namespace: dora-cloudevents
spec:
  template:
    spec:
      containers:
        - image: ko://deployment-frequency-endpoint.go
          env:
            - name: POSTGRESQL_HOST
              value: postgresql
            - name: POSTGRESQL_PASS
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: postgres-password

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: routes
  namespace: dora-cloudevents
data:
  ce-routes.yaml: |
    routes:
      "dev.knative.apiserver.resource.add":
      - http://api-server-to-service-deployment-function.dora-cloudevents.svc.cluster.local
      - http://sockeye.default.svc.cluster.local
      "dev.knative.github.pr.new":
      - http://sockeye.default.svc.cluster.local

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: cloudevents-router-cronjob
  namespace: dora-cloudevents
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cloudevents-router
              image: ko://cloudevents-router.go
              imagePullPolicy: IfNotPresent
              env:
                - name: CE_ROUTES
                  valueFrom:
                    configMapKeyRef:
                      name: routes
                      key: ce-routes.yaml
                - name: POSTGRESQL_HOST
                  value: postgresql
                - name: POSTGRESQL_PASS
                  valueFrom:
                    secretKeyRef:
                      name: postgresql
                      key: postgres-password
          restartPolicy: OnFailure

---

 apiVersion: batch/v1
 kind: CronJob
 metadata:
   name: cdevents-deployment-frequency-cronjob
   namespace: dora-cloudevents
 spec:
   schedule: "* * * * *"
   jobTemplate:
     spec:
       template:
         spec:
           containers:
             - name: cdevents-deployment-frequency
               image: ko://deployment-frequency.go
               imagePullPolicy: IfNotPresent
               env:
                 - name: POSTGRESQL_HOST
                   value: postgresql
                 - name: POSTGRESQL_PASS
                   valueFrom:
                     secretKeyRef:
                       name: postgresql
                       key: postgres-password
           restartPolicy: OnFailure
