apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: admin
spec:
  rules:
   -  http:
        paths:
          - path: /
            pathType: Prefix 
            backend:
              service:
                name: admin 
                port:
                  number: 80
