name: Agenda Service - Service Pipeline
env: 
  KO_DOCKER_REPO: docker.io/salaboy
on:
  push:
    branches: ['main']

jobs:
  publish:
    name: Agenda Service - Service Pipeline 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.21.x'
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2 #https://github.com/dorny/paths-filter
        id: changes
        with:
          filters: |
            src:
              - 'conference-application/agenda-service/**'
      - if: steps.changes.outputs.src == 'true'
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - if: steps.changes.outputs.src == 'true'
        uses: ko-build/setup-ko@v0.6 #https://github.com/ko-build/setup-ko
      - if: steps.changes.outputs.src == 'true'
        env: 
          KO_DOCKER_REPO: docker.io/salaboy
        run: cd conference-application/agenda-service && ko build -t v0.9.9-gh
